CREATE DATABASE IF NOT EXISTS L2;
USE L2;

CREATE TABLE CONTRATOS(
	ID INT(10),
	VALOR_PARCELA INT(6),
	PARCELAS INT(3),
	PRIMARY KEY (ID)
);

CREATE TABLE PESSOAS(
	ID INT(10),
	NOME VARCHAR(40) NOT NULL,
	CONTRATO_ID INT(10) NOT NULL,
	INADIMPLENTE VARCHAR(1) NOT NULL,
	DT_COMPLETO DATE DEFAULT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (CONTRATO_ID) REFERENCES CONTRATOS(ID)
);

CREATE TABLE PAGAMENTOS(
	ID INT(1),
	PESSOA_ID INT(10),
	DT_PAGAMENTO INT(3),
	PRIMARY KEY (ID),
	FOREIGN KEY (PESSOA_ID) REFERENCES PESSOAS(ID)
);

INSERT INTO CONTRATOS VALUES (1, 150, 100);
INSERT INTO CONTRATOS VALUES (2, 300, 48);
INSERT INTO CONTRATOS VALUES (3, 550, 24);
INSERT INTO CONTRATOS VALUES (4, 1000, 12);

INSERT INTO PESSOAS (ID, NOME, CONTRATO_ID, INADIMPLENTE) VALUES (1, 'Cristian Ghyprievy', 2, 'S');
INSERT INTO PESSOAS (ID, NOME, CONTRATO_ID, INADIMPLENTE) VALUES (2, 'Joana Cabel', 1, 'S');
INSERT INTO PESSOAS (ID, NOME, CONTRATO_ID, INADIMPLENTE) VALUES (3, 'John Serial', 3, 'S');
INSERT INTO PESSOAS VALUES (4, 'Michael Seven', 2, 'N', '2021-09-25');

INSERT INTO PAGAMENTOS VALUES (1, 4, '2021-09-01');
INSERT INTO PAGAMENTOS VALUES (2, 3, '2021-09-05');
INSERT INTO PAGAMENTOS VALUES (3, 1, '2021-09-19');
INSERT INTO PAGAMENTOS VALUES (4, 2, '2021-09-25');



SELECT pes.NOME as NOME, cont.VALOR_PARCELA*cont.PARCELAS as VALOR_TOTAL
FROM PESSOAS as pes, CONTRATOS as cont 
WHERE pes.INADIMPLENTE = 'N' && pes.CONTRATO_ID = cont.ID;

SELECT pes.NOME as NOME, DATE_FORMAT(pgt.DT_PAGAMENTO, '%d') as DIA_MES, cont.VALOR_PARCELA as parcela
FROM PESSOAS as pes, PAGAMENTOS as pgt, CONTRATOS as cont
WHERE pes.ID = pgt.PESSOA_ID && pes.INADIMPLENTE = 'S' && pes.CONTRATO_ID = cont.ID;

